#!/bin/bash

outfile="catpdf"
header=

while [[ "$1" =~ ^- ]]; do
	case "$1" in
		-h|--help)
			cat <<_EOF_
$0 [options] file1 file2 ...
Concatenate PDF files.
	-h --help
		Print help and exit.
	-i --infohead
		Include info headers.
	-o --outfile filename
		Specify output file.
_EOF_
			exit
			;;
		-i|--infohead)
			header='\headtrue \headheight16pt'
			shift
			;;
		-o|--outfile)
			outfile="$2"
			shift 2
			;;
		*)
			echo "Unrecognized option $1" >&2
			shift
	esac
done

pdfs=
for pdf in "$@"; do
	[[ -r "$pdf" && "$pdf" =~ \.(pdf|PDF)$ ]] || { echo "$0: warning: skipping file $pdf." >&2; continue; }
	pdfs+="\\inspdf{$pdf}"
done

tee $outfile.tex <<-'_EOF_' >/dev/null
	\catcode`@=11
	\newif\ifhead \newdimen\headheight
	\hoffset-1in \voffset-1in
	\font\fira=FiraMono-Regular-tosf-t1 at 10pt
	\def\inspdf#1{{%
		\toks\z@\expandafter{\detokenize{#1}}\edef\inspdfname{\the\toks\z@}%
		\pdfximage width\pdfpagewidth page\@ne{\inspdfname}%
		\count@\@ne \inspdfpage
		\loop
		\ifnum\count@<\pdflastximagepages
			\advance\count@\@ne
			\pdfximage width\pdfpagewidth page\count@{\inspdfname}%
			\inspdfpage
			\repeat
		}}
	\def\inspdfpage{%
		\pdfpagewidth\pdfximagebbox\pdflastximage\thr@@
		\pdfpageheight\dimexpr\pdfximagebbox\pdflastximage4+\headheight
		\shipout\vbox to\dimexpr
				\pdfximagebbox\pdflastximage4+\headheight
		{\ifhead \vbox to\headheight{\vfil
			\setbox\z@\hbox to\pdfximagebbox\pdflastximage\thr@@{%
				\fira \ \inspdfname\hfil
				\the\count@/\the\pdflastximagepages\ }%
			\dp\z@\z@ \box\z@
			\vfil}\fi
		\pdfrefximage\pdflastximage \vfil}%
	}
_EOF_

echo "$header $pdfs" >> $outfile.tex
echo '\bye' >> $outfile.tex

pdftex --interaction=batchmode $outfile.tex >/dev/null || \
	{ echo "$0: error: pdftex returned nonzero exit status; check $outfile.log." >&2; exit 1; }
rm $outfile.tex $outfile.log

exit 0
