#!/bin/bash

_view() {
	[[ -f "$*" ]] || return
	pdftoppm -png -r 300 -- "$*" "$*"
	( sxiv -- "$*-1.png" >/dev/null 2>&1 & )
}

cd /tmp
tmp=$(mktemp -p .) || exit 1

:	${texcmdline:=pdflatex -interaction nonstopmode -no-shell-escape}

case "$(basename "$0")" in
	,,)
		texpre='\begin{gather*}'; texpost='\end{gather*}'
		;;
	,align)
		texpre='\begin{align*}'; texpost='\end{align*}'
		;;
	*)
		texpre=; texpost=
		;;
esac

cat << _EOF_ > "$tmp"
\documentclass[preview, border=20pt, 12pt]{standalone}
\usepackage{mathtools, amssymb, amsthm}
\begin{document}
$texpre%
$*%
$texpost%
\end{document}
_EOF_

if $texcmdline -jobname "$tmp" -- "$tmp" <&- >/dev/null 2>&1; then
	_view "$tmp.pdf"
else
	ret=$?
	_view "$tmp.pdf"
	grep --color=auto -m 1 -A 5 '^! .*$' -- "$tmp.log" 2>/dev/null
	exit $ret
fi
